FROM docker.io/node:16 as walt-node

RUN mkdir -p /code

WORKDIR /code

ADD web/waltid-idpkit-ui /code

RUN yarn install -g -s --no--progress && \
    yarn build &&  \
    yarn generate

FROM docker.io/nginx:stable

COPY web/waltid-idpkit-ui/nginx.conf /etc/nginx/nginx.conf
COPY --from=walt-node /code/dist /usr/share/nginx/html
EXPOSE 80
