FROM docker.io/node:18 as walt-node

RUN mkdir -p /code

WORKDIR /code

ADD web/waltid-idpkit-ui /code

RUN export NODE_OPTIONS=--openssl-legacy-provider && \
    yarn install -g -s --no--progress && \
    yarn build &&  \
    yarn generate

FROM docker.io/nginx:stable

COPY --from=walt-node /code/dist /usr/share/nginx/html
EXPOSE 80
